/**
 * Wiki 数据 - 客户端安全部分
 *
 * 此文件不包含 Node.js API (fs/path),可被 Client Component 安全导入。
 * 服务端文件系统相关函数见 lib/wiki-server.ts
 */

export interface WikiArticle {
  slug: string;
  category: string;
  url: string;
  date: string; // YYYY-MM-DD (发布日期, 北京时间)
  updatedAt?: string; // YYYY-MM-DD (最后更新日期, 缺省时回退到 date)
  title?: string; // 文章标题 (用于搜索和推荐展示)
  keywords?: string[]; // 搜索关键词
  topic?: string; // 文章主题 (用于相关文章推荐)
}

/**
 * 排期文章列表 (手动维护)
 * 新文章在此登记,配合时间锁实现按日期自动发布
 * date 字段为发布日期 (北京时间)
 */
export const scheduledArticles: WikiArticle[] = [
  // 2026.8.31
  {
    slug: '5-minute-proofreading-check-yki-writing-errors',
    category: 'guides',
    url: '/wiki/guides/5-minute-proofreading-check-yki-writing-errors',
    date: '2026-08-31',
    title: '5-Minute Proofreading: How to Check Your YKI Writing for Errors',
    keywords: ['check YKI writing errors', 'Finnish grammar check', 'YKI exam proofreading', 'Finnish spelling mistakes', 'YKI writing tips'],
    topic: 'yki-test-strategy',
  },
  // 2026.8.30
  {
    slug: 'does-handwriting-matter-yki-writing-test',
    category: 'guides',
    url: '/wiki/guides/does-handwriting-matter-yki-writing-test',
    date: '2026-08-30',
    title: 'Does Handwriting Matter in the YKI Writing Test? | ExamCoach.ai',
    keywords: ['YKI handwriting', 'YKI paper test', 'writing clearly Finnish exam', 'YKI grading criteria', 'YKI test tips'],
    topic: 'yki-test-tips',
  },
  {
    slug: 'what-to-do-if-you-dont-understand-yki-writing-prompt',
    category: 'guides',
    url: '/wiki/guides/what-to-do-if-you-dont-understand-yki-writing-prompt',
    date: '2026-08-30',
    title: 'What to Do If You Don\'t Understand the YKI Writing Prompt',
    keywords: ['YKI writing prompt help', 'guessing meaning Finnish', 'YKI test strategies', 'blank mind YKI', 'YKI writing tips'],
    topic: 'yki-test-strategy',
  },
  {
    slug: 'yki-writing-time-management',
    category: 'guides',
    url: '/wiki/guides/yki-writing-time-management',
    date: '2026-08-30',
    title: 'YKI Writing Time Management: How to Finish All 3 Tasks',
    keywords: ['YKI writing time management', 'YKI test duration', 'pacing YKI writing', 'Finnish exam time limits', 'YKI writing tips'],
    topic: 'yki-test-strategy',
  },
  // 2026.8.29
  {
    slug: 'express-opinion-finnish-yki',
    category: 'templates',
    url: '/wiki/templates/express-opinion-finnish-yki',
    date: '2026-08-29',
    title: 'How to Express Your Opinion in Finnish: YKI Task 3 Templates',
    keywords: ['express opinion Finnish', 'YKI opinion templates', 'minun mielestäni', 'Finnish opinion phrases', 'YKI Task 3'],
    topic: 'opinion-writing',
  },
  // 2026.8.28
  {
    slug: 'yki-linking-words-finnish',
    category: 'templates',
    url: '/wiki/templates/yki-linking-words-finnish',
    date: '2026-08-28',
    title: '30 Essential YKI Linking Words Finnish for High-Scoring Essays',
    keywords: ['YKI linking words', 'Finnish conjunctions', 'YKI essay vocabulary', 'Finnish connectors', 'essay linking words'],
    topic: 'yki-linking-words',
  },
  // 2026.8.27
  {
    slug: 'formal-vs-informal-finnish-yki',
    category: 'guides',
    url: '/wiki/guides/formal-vs-informal-finnish-yki',
    date: '2026-08-27',
    title: 'Formal vs Informal Finnish: What to Use in YKI Writing',
    keywords: ['formal vs informal Finnish', 'kirjakieli puhekieli', 'YKI writing tone', 'Finnish register', 'YKI writing tips'],
    topic: 'formal-vs-informal',
  },
  {
    slug: 'yki-complaint-letter-finnish',
    category: 'guides',
    url: '/wiki/guides/yki-complaint-letter-finnish',
    date: '2026-08-27',
    title: 'How to Write a Complaint Letter in Finnish for YKI Exam',
    keywords: ['YKI complaint letter', 'reklamaatio suomeksi', 'Finnish complaint letter', 'YKI writing phrases', 'formal letter Finnish'],
    topic: 'complaint-letter',
  },
  // 2026.8.26
  {
    slug: 'yki-formal-email-writing-task-2',
    category: 'guides',
    url: '/wiki/guides/yki-formal-email-writing-task-2',
    date: '2026-08-26',
    title: 'YKI Formal Email Writing: Complete Guide for Task 2',
    keywords: ['YKI formal email', 'Task 2 email', 'Finnish formal email', 'YKI writing guide', 'formal email Finnish'],
    topic: 'formal-email',
  },
  {
    slug: 'yki-task-2-email-examples-job-course',
    category: 'essays',
    url: '/wiki/essays/yki-task-2-email-examples-job-course',
    date: '2026-08-26',
    title: 'YKI Task 2 Email Examples: Applying for a Job or Course',
    keywords: ['YKI email examples', 'job application email', 'course application', 'B1 Finnish letter', 'YKI Task 2 examples'],
    topic: 'email-examples',
  },
  // 2026.8.25
  {
    slug: 'finnish-writing-correction-online',
    category: 'guides',
    url: '/wiki/guides/finnish-writing-correction-online',
    date: '2026-08-25',
    title: 'Finnish Writing Correction Online: AI Grammar Feedback',
    keywords: ['Finnish writing correction', 'AI Finnish correction', 'YKI writing check', 'Finnish grammar checker', 'online writing correction'],
    topic: 'ai-writing',
  },
  {
    slug: 'yki-writing-feedback',
    category: 'guides',
    url: '/wiki/guides/yki-writing-feedback',
    date: '2026-08-25',
    title: 'YKI Writing Feedback: How to Fix Your Weaknesses Before Exam',
    keywords: ['YKI writing feedback', 'Finnish writing mistakes', 'YKI improvement', 'writing feedback', 'YKI writing check'],
    topic: 'yki-writing-feedback',
  },
  // 2026.8.24
  {
    slug: 'free-yki-writing-checker',
    category: 'guides',
    url: '/wiki/guides/free-yki-writing-checker',
    date: '2026-08-24',
    title: 'Free YKI Writing Checker Online With AI Feedback',
    keywords: ['free YKI writing checker', 'YKI AI checker', 'Finnish writing correction', 'YKI writing check', 'free Finnish writing checker'],
    topic: 'yki-writing-checker',
  },
  {
    slug: 'ai-finnish-writing-tutor',
    category: 'guides',
    url: '/wiki/guides/ai-finnish-writing-tutor',
    date: '2026-08-24',
    title: 'How to Use AI to Improve Finnish Writing Before YKI Exam',
    keywords: ['AI Finnish writing tutor', 'Finnish AI correction', 'YKI preparation AI', 'AI writing tutor', 'Finnish writing AI'],
    topic: 'ai-writing-tutor',
  },
  // 2026.8.23
  {
    slug: 'yki-writing-answer-template',
    category: 'templates',
    url: '/wiki/templates/yki-writing-answer-template',
    date: '2026-08-23',
    title: 'YKI Writing Answer Template: Structure Every Task',
    keywords: ['YKI writing answer template', 'YKI exam template', 'Finnish writing framework', 'YKI writing structure', 'YKI message format'],
    topic: 'yki-writing-template',
  },
  {
    slug: 'most-common-finnish-words-for-yki-writing-test',
    category: 'templates',
    url: '/wiki/templates/most-common-finnish-words-for-yki-writing-test',
    date: '2026-08-23',
    title: 'Most Common Finnish Words for YKI Writing Test',
    keywords: ['Finnish words for YKI writing', 'YKI vocabulary list', 'Finnish writing vocabulary', 'YKI connectors', 'essential Finnish words'],
    topic: 'yki-vocabulary',
  },
  // 2026.8.22
  {
    slug: 'yki-writing-topics',
    category: 'guides',
    url: '/wiki/guides/yki-writing-topics',
    date: '2026-08-22',
    title: 'YKI Writing Topics: Common Exam Themes and Questions',
    keywords: ['YKI writing topics', 'YKI exam questions', 'Finnish writing themes', 'YKI test topics', 'common YKI writing tasks'],
    topic: 'yki-writing-topics',
  },
  {
    slug: 'yki-writing-practice',
    category: 'guides',
    url: '/wiki/guides/yki-writing-practice',
    date: '2026-08-22',
    title: 'YKI Writing Practice: How to Train With Real Exam Topics',
    keywords: ['YKI writing practice', 'Finnish writing exercises', 'YKI practice topics', 'YKI exam preparation', 'Finnish writing training'],
    topic: 'yki-writing-practice',
  },
  // 2026.8.21
  {
    slug: 'yki-writing-level-4-examples',
    category: 'essays',
    url: '/wiki/essays/yki-writing-level-4-examples',
    date: '2026-08-21',
    title: 'YKI Writing Level 4 Examples: High Score Finnish Answers',
    keywords: ['YKI writing level 4 examples', 'B2 Finnish writing sample', 'YKI advanced writing', 'YKI level 4', 'Finnish exam examples'],
    topic: 'yki-writing-level-4',
  },
  // 2026.8.20
  {
    slug: 'pass-yki-writing-level-3',
    category: 'guides',
    url: '/wiki/guides/pass-yki-writing-level-3',
    date: '2026-08-20',
    title: 'How to Pass YKI Writing Level 3: Complete B1 Strategy',
    keywords: ['pass YKI writing level 3', 'YKI passing score', 'YKI B1 writing', 'Finnish B1 exam', 'YKI writing strategy'],
    topic: 'yki-writing-level-3',
  },
  {
    slug: 'how-to-get-yki-writing-level-4',
    category: 'guides',
    url: '/wiki/guides/how-to-get-yki-writing-level-4',
    date: '2026-08-20',
    title: 'How to Get YKI Writing Level 4: Move From B1 to B2',
    keywords: ['how to get YKI writing level 4', 'YKI B2 writing', 'Finnish advanced writing', 'YKI level 4', 'B1 to B2 Finnish'],
    topic: 'yki-writing-level-4',
  },
  // 2026.8.17
  {
    slug: 'yki-writing-test-checklist',
    category: 'guides',
    url: '/wiki/guides/yki-writing-test-checklist',
    date: '2026-08-17',
    title: 'YKI Writing Test Checklist: Everything You Need Before Exam Day',
    keywords: ['YKI writing test checklist', 'YKI test preparation', 'YKI exam tips', 'Finnish exam day', 'YKI writing test'],
    topic: 'yki-writing-checklist',
  },
  // 2026.8.16
  {
    slug: 'how-long-to-prepare-for-yki-writing-test',
    category: 'guides',
    url: '/wiki/guides/how-long-to-prepare-for-yki-writing-test',
    date: '2026-08-16',
    title: 'How Long Does It Take to Prepare for YKI Writing Test?',
    keywords: ['how long to prepare for YKI writing', 'YKI preparation time', 'YKI B1 writing preparation', 'YKI writing test', 'Finnish language exam'],
    topic: 'yki-writing-preparation',
  },
  {
    slug: 'yki-writing-preparation-plan',
    category: 'guides',
    url: '/wiki/guides/yki-writing-preparation-plan',
    date: '2026-08-16',
    title: 'YKI Writing Preparation Plan: 30-Day Study Schedule for B1-B2',
    keywords: ['YKI writing preparation plan', 'YKI study schedule', 'YKI B1 writing preparation', 'Finnish exam preparation', 'YKI writing practice plan'],
    topic: 'yki-writing-preparation',
  },
  // 2026.8.15
  {
    slug: 'finnish-language-test-citizenship',
    category: 'guides',
    url: '/wiki/guides/finnish-language-test-citizenship',
    date: '2026-08-15',
    title: 'Finnish Language Test for Citizenship: Complete YKI Guide',
    keywords: ['Finnish language test citizenship', 'YKI citizenship requirement', 'Finnish citizenship exam', 'YKI test', 'Finnish citizenship language requirement'],
    topic: 'yki-citizenship',
  },
  // 2026.8.14
  {
    slug: 'yki-exam-tips',
    category: 'guides',
    url: '/wiki/guides/yki-exam-tips',
    date: '2026-08-14',
    title: 'YKI Exam Tips: How to Prepare Efficiently',
    keywords: ['YKI exam tips', 'YKI preparation', 'Finnish test strategy', 'YKI test', 'Finnish exam preparation'],
    topic: 'yki-exam-tips',
  },
  {
    slug: 'yki-level-3-vs-level-4',
    category: 'scoring',
    url: '/wiki/scoring/yki-level-3-vs-level-4',
    date: '2026-08-14',
    title: 'YKI Level 3 vs Level 4: What Score Do You Need?',
    keywords: ['YKI level 3 vs level 4', 'YKI scoring', 'Finnish language levels', 'YKI keskitaso', 'YKI citizenship requirement'],
    topic: 'yki-scoring-levels',
  },
  // 2026.8.13
  {
    slug: 'how-to-pass-yki-test',
    category: 'guides',
    url: '/wiki/guides/how-to-pass-yki-test',
    date: '2026-08-13',
    title: 'How to Pass YKI Test: Complete Intermediate Strategy Guide',
    keywords: ['how to pass YKI test', 'YKI keskitaso preparation', 'Finnish exam tips', 'YKI test Finnish citizenship', 'YKI speaking templates'],
    topic: 'yki-test-strategy',
  },
  {
    slug: 'yki-test-preparation-plan',
    category: 'guides',
    url: '/wiki/guides/yki-test-preparation-plan',
    date: '2026-08-13',
    title: 'YKI Test Preparation Plan: 30 Day Study Schedule',
    keywords: ['YKI test preparation plan', 'YKI study schedule', 'Finnish exam preparation', 'YKI keskitaso plan', 'how to study for YKI'],
    topic: 'yki-preparation-plan',
  },
  // 2026.8.12
  {
    slug: 'yki-speaking-scoring',
    category: 'scoring',
    url: '/wiki/scoring/yki-speaking-scoring',
    date: '2026-08-12',
    title: 'How YKI Speaking is Scored: Examiner Criteria Explained',
    keywords: ['YKI speaking scoring', 'YKI oral assessment', 'Finnish speaking evaluation', 'YKI test preparation'],
    topic: 'speaking-scoring',
  },
  {
    slug: 'yki-speaking-mistakes',
    category: 'guides',
    url: '/wiki/guides/yki-speaking-mistakes',
    date: '2026-08-12',
    title: 'Common YKI Speaking Mistakes and How to Improve',
    keywords: ['YKI speaking mistakes', 'Finnish speaking errors', 'YKI speaking test', 'YKI preparation', 'common YKI mistakes'],
    topic: 'speaking-mistakes',
  },
  // 2026.8.11
  {
    slug: 'finnish-speaking-phrases-yki',
    category: 'templates',
    url: '/wiki/templates/finnish-speaking-phrases-yki',
    date: '2026-08-11',
    title: 'Finnish Speaking Phrases for YKI Test',
    keywords: ['Finnish speaking phrases YKI', 'YKI vocabulary', 'Finnish conversation phrases', 'YKI speaking test', 'Finnish exam phrases'],
    topic: 'speaking-phrases',
  },
  {
    slug: 'yki-speaking-templates',
    category: 'templates',
    url: '/wiki/templates/yki-speaking-templates',
    date: '2026-08-11',
    title: 'YKI Speaking Templates: Useful Finnish Speaking Structures',
    keywords: ['YKI speaking templates', 'Finnish speaking phrases', 'YKI speaking answers', 'YKI speaking test', 'Finnish speaking structures'],
    topic: 'speaking-templates',
  },
  // 2026.8.04
  {
    slug: 'ai-yki-writing-preparation',
    category: 'guides',
    url: '/wiki/guides/ai-yki-writing-preparation',
    date: '2026-08-04',
    title: 'How AI Can Help You Prepare for the YKI Writing Test',
    keywords: ['ai', 'yki', 'writing', 'preparation', 'ai-assisted'],
    topic: 'ai-writing',
  },
  {
    slug: 'practice-yki-writing-online',
    category: 'guides',
    url: '/wiki/guides/practice-yki-writing-online',
    date: '2026-08-04',
    title: 'Practice YKI Writing Online With AI Feedback',
    keywords: ['practice', 'yki', 'writing', 'online', 'ai feedback'],
    topic: 'ai-writing',
  },
  // 2026.8.05
  {
    slug: 'check-finnish-writing-level-online',
    category: 'guides',
    url: '/wiki/guides/check-finnish-writing-level-online',
    date: '2026-08-05',
    title: 'Check Finnish Writing Level Online With AI Evaluation',
    keywords: ['check', 'finnish', 'writing', 'level', 'online', 'ai'],
    topic: 'ai-writing',
  },
  {
    slug: 'yki-writing-feedback-guide',
    category: 'guides',
    url: '/wiki/guides/yki-writing-feedback-guide',
    date: '2026-08-05',
    title: 'YKI Writing Feedback Guide: Understand Your AI Examiner Report',
    keywords: ['yki', 'writing', 'feedback', 'guide', 'ai examiner'],
    topic: 'ai-writing',
  },
  // 2026.8.06
  {
    slug: 'how-to-write-message-yki',
    category: 'guides',
    url: '/wiki/guides/how-to-write-message-yki',
    date: '2026-08-06',
    title: 'How to Write a Message for YKI Writing Test',
    keywords: ['how to', 'write', 'message', 'yki', 'writing test'],
    topic: 'message-writing',
  },
  {
    slug: 'yki-message-writing-guide',
    category: 'guides',
    url: '/wiki/guides/yki-message-writing-guide',
    date: '2026-08-06',
    title: 'YKI Message Writing Guide: How to Write Short Messages in Finnish',
    keywords: ['yki', 'message', 'writing', 'guide', 'finnish', 'short message'],
    topic: 'message-writing',
  },
  // 2026.8.07
  {
    slug: 'yki-message-template',
    category: 'templates',
    url: '/wiki/templates/yki-message-template',
    date: '2026-08-07',
    title: 'YKI Message Template: Finnish Short Message Structures',
    keywords: ['yki', 'message', 'template', 'finnish', 'structure'],
    topic: 'message-writing',
  },
  {
    slug: 'yki-message-writing-examples',
    category: 'essays',
    url: '/wiki/essays/yki-message-writing-examples',
    date: '2026-08-07',
    title: 'YKI Message Writing Examples: Finnish Sample Answers Explained',
    keywords: ['yki', 'message', 'writing', 'examples', 'sample', 'finnish'],
    topic: 'message-writing',
  },
  // 2026.8.08
  {
    slug: 'finnish-message-phrases-yki',
    category: 'templates',
    url: '/wiki/templates/finnish-message-phrases-yki',
    date: '2026-08-08',
    title: 'Finnish Message Phrases for YKI Writing Test',
    keywords: ['finnish', 'message', 'phrases', 'yki', 'writing'],
    topic: 'message-writing',
  },
  // 2026.8.09
  {
    slug: 'yki-message-writing-mistakes',
    category: 'guides',
    url: '/wiki/guides/yki-message-writing-mistakes',
    date: '2026-08-09',
    title: 'Common YKI Message Writing Mistakes Students Make',
    keywords: ['yki', 'message', 'writing', 'mistakes', 'common'],
    topic: 'message-writing',
  },
  {
    slug: 'yki-message-writing-scoring',
    category: 'scoring',
    url: '/wiki/scoring/yki-message-writing-scoring',
    date: '2026-08-09',
    title: 'YKI Message Writing Scoring: How Examiners Evaluate Messages',
    keywords: ['yki', 'message', 'writing', 'scoring', 'examiners'],
    topic: 'message-writing',
  },
  // 2026.8.10
  {
    slug: 'yki-speaking-examples',
    category: 'essays',
    url: '/wiki/essays/yki-speaking-examples',
    date: '2026-08-10',
    title: 'YKI Speaking Examples: Finnish Speaking Answers for B1-B2',
    keywords: ['yki', 'speaking', 'examples', 'finnish', 'b1', 'b2'],
    topic: 'speaking',
  },
  {
    slug: 'yki-writing-task-3',
    category: 'guides',
    url: '/wiki/guides/yki-writing-task-3',
    date: '2026-08-10',
    title: 'YKI Writing Task 3 Explained: Complete Message Preparation Guide',
    keywords: ['yki', 'writing', 'task 3', 'message', 'preparation'],
    topic: 'message-writing',
  },
  // 2026.7.28
  {
    slug: 'how-to-write-an-opinion-text-in-finnish',
    category: 'guides',
    url: '/wiki/guides/how-to-write-an-opinion-text-in-finnish',
    date: '2026-07-28',
    title: 'How to Write an Opinion Text in Finnish: YKI Writing Task 2 Strategy',
    keywords: ['how to', 'write', 'opinion', 'text', 'finnish', 'yki', 'task 2'],
    topic: 'opinion-writing',
  },
  {
    slug: 'yki-opinion-essay-structure',
    category: 'guides',
    url: '/wiki/guides/yki-opinion-essay-structure',
    date: '2026-07-28',
    title: 'YKI Opinion Essay Structure: B1-B2 Writing Framework Explained',
    keywords: ['yki', 'opinion', 'essay', 'structure', 'b1', 'b2', 'framework'],
    topic: 'opinion-writing',
  },
  {
    slug: 'yki-opinion-essay-templates',
    category: 'templates',
    url: '/wiki/templates/yki-opinion-essay-templates',
    date: '2026-07-29',
    title: 'YKI Opinion Essay Templates: Finnish Writing Frameworks for B1-B2',
    keywords: ['yki', 'opinion', 'essay', 'templates', 'finnish', 'b1', 'b2'],
    topic: 'opinion-writing',
  },
  {
    slug: 'yki-opinion-writing-examples',
    category: 'essays',
    url: '/wiki/essays/yki-opinion-writing-examples',
    date: '2026-07-29',
    title: 'YKI Opinion Writing Examples: Finnish B1-B2 Sample Essays',
    keywords: ['yki', 'opinion', 'writing', 'examples', 'finnish', 'sample', 'b1', 'b2'],
    topic: 'opinion-writing',
  },
  {
    slug: 'finnish-opinion-writing-phrases',
    category: 'templates',
    url: '/wiki/templates/finnish-opinion-writing-phrases',
    date: '2026-07-30',
    title: 'Finnish Opinion Writing Phrases for YKI Exam Success',
    keywords: ['finnish', 'opinion', 'writing', 'phrases', 'yki', 'exam'],
    topic: 'opinion-writing',
  },
  {
    slug: 'yki-opinion-writing-scoring',
    category: 'scoring',
    url: '/wiki/scoring/yki-opinion-writing-scoring',
    date: '2026-07-30',
    title: 'YKI Opinion Writing Scoring: How Examiners Grade Your Essay',
    keywords: ['yki', 'opinion', 'writing', 'scoring', 'examiners', 'grade'],
    topic: 'opinion-writing',
  },
  {
    slug: 'common-yki-opinion-writing-mistakes',
    category: 'guides',
    url: '/wiki/guides/common-yki-opinion-writing-mistakes',
    date: '2026-07-31',
    title: 'Common YKI Opinion Writing Mistakes and How to Avoid Them',
    keywords: ['common', 'yki', 'opinion', 'writing', 'mistakes', 'avoid'],
    topic: 'opinion-writing',
  },
  {
    slug: 'yki-b1-vocabulary-list-writing-test',
    category: 'templates',
    url: '/wiki/templates/yki-b1-vocabulary-list-writing-test',
    date: '2026-07-31',
    title: 'YKI B1 Vocabulary List: Essential Finnish Words for Writing Test',
    keywords: ['yki', 'b1', 'vocabulary', 'list', 'finnish', 'words', 'writing'],
    topic: 'vocabulary',
  },
  {
    slug: 'finnish-connectors-for-writing',
    category: 'templates',
    url: '/wiki/templates/finnish-connectors-for-writing',
    date: '2026-08-01',
    title: 'Finnish Connectors for Writing: Improve Your YKI Essay Flow',
    keywords: ['finnish', 'connectors', 'writing', 'yki', 'essay', 'flow'],
    topic: 'vocabulary',
  },
  {
    slug: 'yki-b2-vocabulary-list-advanced-finnish-words',
    category: 'templates',
    url: '/wiki/templates/yki-b2-vocabulary-list-advanced-finnish-words',
    date: '2026-08-01',
    title: 'YKI B2 Vocabulary List: Advanced Finnish Words for Writing',
    keywords: ['yki', 'b2', 'vocabulary', 'list', 'advanced', 'finnish', 'words'],
    topic: 'vocabulary',
  },
  {
    slug: 'common-finnish-writing-errors-yki-students',
    category: 'guides',
    url: '/wiki/guides/common-finnish-writing-errors-yki-students',
    date: '2026-08-02',
    title: 'Common Finnish Writing Errors YKI Students Should Avoid',
    keywords: ['common', 'finnish', 'writing', 'errors', 'yki', 'students'],
    topic: 'writing-errors',
  },
  {
    slug: 'finnish-writing-transition-words-yki-exam',
    category: 'templates',
    url: '/wiki/templates/finnish-writing-transition-words-yki-exam',
    date: '2026-08-02',
    title: 'Finnish Writing Transition Words for YKI Exam',
    keywords: ['finnish', 'writing', 'transition', 'words', 'yki', 'exam'],
    topic: 'vocabulary',
  },
  {
    slug: 'ai-yki-writing-checker',
    category: 'guides',
    url: '/wiki/guides/ai-yki-writing-checker',
    date: '2026-08-03',
    title: 'AI YKI Writing Checker: Check Your Finnish Writing Level Instantly',
    keywords: ['ai', 'yki', 'writing', 'checker', 'finnish', 'level', 'online'],
    topic: 'ai-writing',
  },
  {
    slug: 'how-to-improve-finnish-writing-skills-yki-test',
    category: 'guides',
    url: '/wiki/guides/how-to-improve-finnish-writing-skills-yki-test',
    date: '2026-08-03',
    title: 'How to Improve Finnish Writing Skills for YKI Test',
    keywords: ['how to', 'improve', 'finnish', 'writing', 'skills', 'yki', 'test'],
    topic: 'writing-skills',
  },
];
